// automatically generated by the FlatBuffers compiler, do not modify

package Ps;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Position extends Table {
  public static Position getRootAsPosition(ByteBuffer _bb) { return getRootAsPosition(_bb, new Position()); }
  public static Position getRootAsPosition(ByteBuffer _bb, Position obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Position __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long positionId() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public String secName() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer secNameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public int accountId() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public double posQty() { int o = __offset(10); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double avgCost() { int o = __offset(12); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }
  public double mv() { int o = __offset(14); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createPosition(FlatBufferBuilder builder,
      long positionId,
      int secNameOffset,
      int accountId,
      double posQty,
      double avgCost,
      double mv) {
    builder.startObject(6);
    Position.addMv(builder, mv);
    Position.addAvgCost(builder, avgCost);
    Position.addPosQty(builder, posQty);
    Position.addPositionId(builder, positionId);
    Position.addAccountId(builder, accountId);
    Position.addSecName(builder, secNameOffset);
    return Position.endPosition(builder);
  }

  public static void startPosition(FlatBufferBuilder builder) { builder.startObject(6); }
  public static void addPositionId(FlatBufferBuilder builder, long positionId) { builder.addLong(0, positionId, 0L); }
  public static void addSecName(FlatBufferBuilder builder, int secNameOffset) { builder.addOffset(1, secNameOffset, 0); }
  public static void addAccountId(FlatBufferBuilder builder, int accountId) { builder.addInt(2, accountId, 0); }
  public static void addPosQty(FlatBufferBuilder builder, double posQty) { builder.addDouble(3, posQty, 0.0); }
  public static void addAvgCost(FlatBufferBuilder builder, double avgCost) { builder.addDouble(4, avgCost, 0.0); }
  public static void addMv(FlatBufferBuilder builder, double mv) { builder.addDouble(5, mv, 0.0); }
  public static int endPosition(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
  public static void finishPositionBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
}

