// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: examples.proto

#ifndef PROTOBUF_examples_2eproto__INCLUDED
#define PROTOBUF_examples_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace examples {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_examples_2eproto();
void protobuf_AssignDesc_examples_2eproto();
void protobuf_ShutdownFile_examples_2eproto();

class PbMsg;

// ===================================================================

class PbMsg : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:examples.PbMsg) */ {
 public:
  PbMsg();
  virtual ~PbMsg();

  PbMsg(const PbMsg& from);

  inline PbMsg& operator=(const PbMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PbMsg& default_instance();

  void Swap(PbMsg* other);

  // implements Message ----------------------------------------------

  inline PbMsg* New() const { return New(NULL); }

  PbMsg* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PbMsg& from);
  void MergeFrom(const PbMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PbMsg* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string pb_str = 1;
  bool has_pb_str() const;
  void clear_pb_str();
  static const int kPbStrFieldNumber = 1;
  const ::std::string& pb_str() const;
  void set_pb_str(const ::std::string& value);
  void set_pb_str(const char* value);
  void set_pb_str(const char* value, size_t size);
  ::std::string* mutable_pb_str();
  ::std::string* release_pb_str();
  void set_allocated_pb_str(::std::string* pb_str);

  // required int32 pb_int = 2;
  bool has_pb_int() const;
  void clear_pb_int();
  static const int kPbIntFieldNumber = 2;
  ::google::protobuf::int32 pb_int() const;
  void set_pb_int(::google::protobuf::int32 value);

  // required int64 pb_ll = 3;
  bool has_pb_ll() const;
  void clear_pb_ll();
  static const int kPbLlFieldNumber = 3;
  ::google::protobuf::int64 pb_ll() const;
  void set_pb_ll(::google::protobuf::int64 value);

  // required bool pb_bool = 4;
  bool has_pb_bool() const;
  void clear_pb_bool();
  static const int kPbBoolFieldNumber = 4;
  bool pb_bool() const;
  void set_pb_bool(bool value);

  // repeated int32 pb_vec_int = 5;
  int pb_vec_int_size() const;
  void clear_pb_vec_int();
  static const int kPbVecIntFieldNumber = 5;
  ::google::protobuf::int32 pb_vec_int(int index) const;
  void set_pb_vec_int(int index, ::google::protobuf::int32 value);
  void add_pb_vec_int(::google::protobuf::int32 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      pb_vec_int() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_pb_vec_int();

  // @@protoc_insertion_point(class_scope:examples.PbMsg)
 private:
  inline void set_has_pb_str();
  inline void clear_has_pb_str();
  inline void set_has_pb_int();
  inline void clear_has_pb_int();
  inline void set_has_pb_ll();
  inline void clear_has_pb_ll();
  inline void set_has_pb_bool();
  inline void clear_has_pb_bool();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr pb_str_;
  ::google::protobuf::int64 pb_ll_;
  ::google::protobuf::int32 pb_int_;
  bool pb_bool_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > pb_vec_int_;
  friend void  protobuf_AddDesc_examples_2eproto();
  friend void protobuf_AssignDesc_examples_2eproto();
  friend void protobuf_ShutdownFile_examples_2eproto();

  void InitAsDefaultInstance();
  static PbMsg* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// PbMsg

// required string pb_str = 1;
inline bool PbMsg::has_pb_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PbMsg::set_has_pb_str() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PbMsg::clear_has_pb_str() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PbMsg::clear_pb_str() {
  pb_str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pb_str();
}
inline const ::std::string& PbMsg::pb_str() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_str)
  return pb_str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbMsg::set_pb_str(const ::std::string& value) {
  set_has_pb_str();
  pb_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_str)
}
inline void PbMsg::set_pb_str(const char* value) {
  set_has_pb_str();
  pb_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:examples.PbMsg.pb_str)
}
inline void PbMsg::set_pb_str(const char* value, size_t size) {
  set_has_pb_str();
  pb_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:examples.PbMsg.pb_str)
}
inline ::std::string* PbMsg::mutable_pb_str() {
  set_has_pb_str();
  // @@protoc_insertion_point(field_mutable:examples.PbMsg.pb_str)
  return pb_str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PbMsg::release_pb_str() {
  // @@protoc_insertion_point(field_release:examples.PbMsg.pb_str)
  clear_has_pb_str();
  return pb_str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PbMsg::set_allocated_pb_str(::std::string* pb_str) {
  if (pb_str != NULL) {
    set_has_pb_str();
  } else {
    clear_has_pb_str();
  }
  pb_str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pb_str);
  // @@protoc_insertion_point(field_set_allocated:examples.PbMsg.pb_str)
}

// required int32 pb_int = 2;
inline bool PbMsg::has_pb_int() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PbMsg::set_has_pb_int() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PbMsg::clear_has_pb_int() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PbMsg::clear_pb_int() {
  pb_int_ = 0;
  clear_has_pb_int();
}
inline ::google::protobuf::int32 PbMsg::pb_int() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_int)
  return pb_int_;
}
inline void PbMsg::set_pb_int(::google::protobuf::int32 value) {
  set_has_pb_int();
  pb_int_ = value;
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_int)
}

// required int64 pb_ll = 3;
inline bool PbMsg::has_pb_ll() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PbMsg::set_has_pb_ll() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PbMsg::clear_has_pb_ll() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PbMsg::clear_pb_ll() {
  pb_ll_ = GOOGLE_LONGLONG(0);
  clear_has_pb_ll();
}
inline ::google::protobuf::int64 PbMsg::pb_ll() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_ll)
  return pb_ll_;
}
inline void PbMsg::set_pb_ll(::google::protobuf::int64 value) {
  set_has_pb_ll();
  pb_ll_ = value;
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_ll)
}

// required bool pb_bool = 4;
inline bool PbMsg::has_pb_bool() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PbMsg::set_has_pb_bool() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PbMsg::clear_has_pb_bool() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PbMsg::clear_pb_bool() {
  pb_bool_ = false;
  clear_has_pb_bool();
}
inline bool PbMsg::pb_bool() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_bool)
  return pb_bool_;
}
inline void PbMsg::set_pb_bool(bool value) {
  set_has_pb_bool();
  pb_bool_ = value;
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_bool)
}

// repeated int32 pb_vec_int = 5;
inline int PbMsg::pb_vec_int_size() const {
  return pb_vec_int_.size();
}
inline void PbMsg::clear_pb_vec_int() {
  pb_vec_int_.Clear();
}
inline ::google::protobuf::int32 PbMsg::pb_vec_int(int index) const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_vec_int)
  return pb_vec_int_.Get(index);
}
inline void PbMsg::set_pb_vec_int(int index, ::google::protobuf::int32 value) {
  pb_vec_int_.Set(index, value);
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_vec_int)
}
inline void PbMsg::add_pb_vec_int(::google::protobuf::int32 value) {
  pb_vec_int_.Add(value);
  // @@protoc_insertion_point(field_add:examples.PbMsg.pb_vec_int)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PbMsg::pb_vec_int() const {
  // @@protoc_insertion_point(field_list:examples.PbMsg.pb_vec_int)
  return pb_vec_int_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PbMsg::mutable_pb_vec_int() {
  // @@protoc_insertion_point(field_mutable_list:examples.PbMsg.pb_vec_int)
  return &pb_vec_int_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace examples

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_examples_2eproto__INCLUDED
