// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: examples.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "examples.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace examples {

namespace {

const ::google::protobuf::Descriptor* PbMsg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PbMsg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_examples_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_examples_2eproto() {
  protobuf_AddDesc_examples_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "examples.proto");
  GOOGLE_CHECK(file != NULL);
  PbMsg_descriptor_ = file->message_type(0);
  static const int PbMsg_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbMsg, pb_str_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbMsg, pb_int_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbMsg, pb_ll_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbMsg, pb_bool_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbMsg, pb_vec_int_),
  };
  PbMsg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PbMsg_descriptor_,
      PbMsg::default_instance_,
      PbMsg_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbMsg, _has_bits_[0]),
      -1,
      -1,
      sizeof(PbMsg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PbMsg, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_examples_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PbMsg_descriptor_, &PbMsg::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_examples_2eproto() {
  delete PbMsg::default_instance_;
  delete PbMsg_reflection_;
}

void protobuf_AddDesc_examples_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_examples_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016examples.proto\022\010examples\"[\n\005PbMsg\022\016\n\006p"
    "b_str\030\001 \002(\t\022\016\n\006pb_int\030\002 \002(\005\022\r\n\005pb_ll\030\003 \002"
    "(\003\022\017\n\007pb_bool\030\004 \002(\010\022\022\n\npb_vec_int\030\005 \003(\005", 119);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "examples.proto", &protobuf_RegisterTypes);
  PbMsg::default_instance_ = new PbMsg();
  PbMsg::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_examples_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_examples_2eproto {
  StaticDescriptorInitializer_examples_2eproto() {
    protobuf_AddDesc_examples_2eproto();
  }
} static_descriptor_initializer_examples_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PbMsg::kPbStrFieldNumber;
const int PbMsg::kPbIntFieldNumber;
const int PbMsg::kPbLlFieldNumber;
const int PbMsg::kPbBoolFieldNumber;
const int PbMsg::kPbVecIntFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PbMsg::PbMsg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:examples.PbMsg)
}

void PbMsg::InitAsDefaultInstance() {
}

PbMsg::PbMsg(const PbMsg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:examples.PbMsg)
}

void PbMsg::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  pb_str_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  pb_int_ = 0;
  pb_ll_ = GOOGLE_LONGLONG(0);
  pb_bool_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PbMsg::~PbMsg() {
  // @@protoc_insertion_point(destructor:examples.PbMsg)
  SharedDtor();
}

void PbMsg::SharedDtor() {
  pb_str_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PbMsg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PbMsg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PbMsg_descriptor_;
}

const PbMsg& PbMsg::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_examples_2eproto();
  return *default_instance_;
}

PbMsg* PbMsg::default_instance_ = NULL;

PbMsg* PbMsg::New(::google::protobuf::Arena* arena) const {
  PbMsg* n = new PbMsg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PbMsg::Clear() {
// @@protoc_insertion_point(message_clear_start:examples.PbMsg)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PbMsg, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PbMsg*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 15u) {
    ZR_(pb_ll_, pb_bool_);
    if (has_pb_str()) {
      pb_str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
  }

#undef ZR_HELPER_
#undef ZR_

  pb_vec_int_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool PbMsg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:examples.PbMsg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string pb_str = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_pb_str()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->pb_str().data(), this->pb_str().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "examples.PbMsg.pb_str");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_pb_int;
        break;
      }

      // required int32 pb_int = 2;
      case 2: {
        if (tag == 16) {
         parse_pb_int:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &pb_int_)));
          set_has_pb_int();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_pb_ll;
        break;
      }

      // required int64 pb_ll = 3;
      case 3: {
        if (tag == 24) {
         parse_pb_ll:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &pb_ll_)));
          set_has_pb_ll();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_pb_bool;
        break;
      }

      // required bool pb_bool = 4;
      case 4: {
        if (tag == 32) {
         parse_pb_bool:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &pb_bool_)));
          set_has_pb_bool();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_pb_vec_int;
        break;
      }

      // repeated int32 pb_vec_int = 5;
      case 5: {
        if (tag == 40) {
         parse_pb_vec_int:
          DO_((::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 1, 40, input, this->mutable_pb_vec_int())));
        } else if (tag == 42) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPackedPrimitiveNoInline<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, this->mutable_pb_vec_int())));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_pb_vec_int;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:examples.PbMsg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:examples.PbMsg)
  return false;
#undef DO_
}

void PbMsg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:examples.PbMsg)
  // required string pb_str = 1;
  if (has_pb_str()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pb_str().data(), this->pb_str().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "examples.PbMsg.pb_str");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->pb_str(), output);
  }

  // required int32 pb_int = 2;
  if (has_pb_int()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->pb_int(), output);
  }

  // required int64 pb_ll = 3;
  if (has_pb_ll()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->pb_ll(), output);
  }

  // required bool pb_bool = 4;
  if (has_pb_bool()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->pb_bool(), output);
  }

  // repeated int32 pb_vec_int = 5;
  for (int i = 0; i < this->pb_vec_int_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(
      5, this->pb_vec_int(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:examples.PbMsg)
}

::google::protobuf::uint8* PbMsg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:examples.PbMsg)
  // required string pb_str = 1;
  if (has_pb_str()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->pb_str().data(), this->pb_str().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "examples.PbMsg.pb_str");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->pb_str(), target);
  }

  // required int32 pb_int = 2;
  if (has_pb_int()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->pb_int(), target);
  }

  // required int64 pb_ll = 3;
  if (has_pb_ll()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->pb_ll(), target);
  }

  // required bool pb_bool = 4;
  if (has_pb_bool()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->pb_bool(), target);
  }

  // repeated int32 pb_vec_int = 5;
  for (int i = 0; i < this->pb_vec_int_size(); i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteInt32ToArray(5, this->pb_vec_int(i), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:examples.PbMsg)
  return target;
}

int PbMsg::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:examples.PbMsg)
  int total_size = 0;

  if (has_pb_str()) {
    // required string pb_str = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pb_str());
  }

  if (has_pb_int()) {
    // required int32 pb_int = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pb_int());
  }

  if (has_pb_ll()) {
    // required int64 pb_ll = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->pb_ll());
  }

  if (has_pb_bool()) {
    // required bool pb_bool = 4;
    total_size += 1 + 1;
  }

  return total_size;
}
int PbMsg::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:examples.PbMsg)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required string pb_str = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->pb_str());

    // required int32 pb_int = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->pb_int());

    // required int64 pb_ll = 3;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->pb_ll());

    // required bool pb_bool = 4;
    total_size += 1 + 1;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated int32 pb_vec_int = 5;
  {
    int data_size = 0;
    for (int i = 0; i < this->pb_vec_int_size(); i++) {
      data_size += ::google::protobuf::internal::WireFormatLite::
        Int32Size(this->pb_vec_int(i));
    }
    total_size += 1 * this->pb_vec_int_size() + data_size;
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PbMsg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:examples.PbMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PbMsg* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PbMsg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:examples.PbMsg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:examples.PbMsg)
    MergeFrom(*source);
  }
}

void PbMsg::MergeFrom(const PbMsg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:examples.PbMsg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  pb_vec_int_.MergeFrom(from.pb_vec_int_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_pb_str()) {
      set_has_pb_str();
      pb_str_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.pb_str_);
    }
    if (from.has_pb_int()) {
      set_pb_int(from.pb_int());
    }
    if (from.has_pb_ll()) {
      set_pb_ll(from.pb_ll());
    }
    if (from.has_pb_bool()) {
      set_pb_bool(from.pb_bool());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void PbMsg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:examples.PbMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PbMsg::CopyFrom(const PbMsg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:examples.PbMsg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PbMsg::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void PbMsg::Swap(PbMsg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PbMsg::InternalSwap(PbMsg* other) {
  pb_str_.Swap(&other->pb_str_);
  std::swap(pb_int_, other->pb_int_);
  std::swap(pb_ll_, other->pb_ll_);
  std::swap(pb_bool_, other->pb_bool_);
  pb_vec_int_.UnsafeArenaSwap(&other->pb_vec_int_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PbMsg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PbMsg_descriptor_;
  metadata.reflection = PbMsg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PbMsg

// required string pb_str = 1;
bool PbMsg::has_pb_str() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void PbMsg::set_has_pb_str() {
  _has_bits_[0] |= 0x00000001u;
}
void PbMsg::clear_has_pb_str() {
  _has_bits_[0] &= ~0x00000001u;
}
void PbMsg::clear_pb_str() {
  pb_str_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_pb_str();
}
 const ::std::string& PbMsg::pb_str() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_str)
  return pb_str_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PbMsg::set_pb_str(const ::std::string& value) {
  set_has_pb_str();
  pb_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_str)
}
 void PbMsg::set_pb_str(const char* value) {
  set_has_pb_str();
  pb_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:examples.PbMsg.pb_str)
}
 void PbMsg::set_pb_str(const char* value, size_t size) {
  set_has_pb_str();
  pb_str_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:examples.PbMsg.pb_str)
}
 ::std::string* PbMsg::mutable_pb_str() {
  set_has_pb_str();
  // @@protoc_insertion_point(field_mutable:examples.PbMsg.pb_str)
  return pb_str_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PbMsg::release_pb_str() {
  // @@protoc_insertion_point(field_release:examples.PbMsg.pb_str)
  clear_has_pb_str();
  return pb_str_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PbMsg::set_allocated_pb_str(::std::string* pb_str) {
  if (pb_str != NULL) {
    set_has_pb_str();
  } else {
    clear_has_pb_str();
  }
  pb_str_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), pb_str);
  // @@protoc_insertion_point(field_set_allocated:examples.PbMsg.pb_str)
}

// required int32 pb_int = 2;
bool PbMsg::has_pb_int() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void PbMsg::set_has_pb_int() {
  _has_bits_[0] |= 0x00000002u;
}
void PbMsg::clear_has_pb_int() {
  _has_bits_[0] &= ~0x00000002u;
}
void PbMsg::clear_pb_int() {
  pb_int_ = 0;
  clear_has_pb_int();
}
 ::google::protobuf::int32 PbMsg::pb_int() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_int)
  return pb_int_;
}
 void PbMsg::set_pb_int(::google::protobuf::int32 value) {
  set_has_pb_int();
  pb_int_ = value;
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_int)
}

// required int64 pb_ll = 3;
bool PbMsg::has_pb_ll() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void PbMsg::set_has_pb_ll() {
  _has_bits_[0] |= 0x00000004u;
}
void PbMsg::clear_has_pb_ll() {
  _has_bits_[0] &= ~0x00000004u;
}
void PbMsg::clear_pb_ll() {
  pb_ll_ = GOOGLE_LONGLONG(0);
  clear_has_pb_ll();
}
 ::google::protobuf::int64 PbMsg::pb_ll() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_ll)
  return pb_ll_;
}
 void PbMsg::set_pb_ll(::google::protobuf::int64 value) {
  set_has_pb_ll();
  pb_ll_ = value;
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_ll)
}

// required bool pb_bool = 4;
bool PbMsg::has_pb_bool() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void PbMsg::set_has_pb_bool() {
  _has_bits_[0] |= 0x00000008u;
}
void PbMsg::clear_has_pb_bool() {
  _has_bits_[0] &= ~0x00000008u;
}
void PbMsg::clear_pb_bool() {
  pb_bool_ = false;
  clear_has_pb_bool();
}
 bool PbMsg::pb_bool() const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_bool)
  return pb_bool_;
}
 void PbMsg::set_pb_bool(bool value) {
  set_has_pb_bool();
  pb_bool_ = value;
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_bool)
}

// repeated int32 pb_vec_int = 5;
int PbMsg::pb_vec_int_size() const {
  return pb_vec_int_.size();
}
void PbMsg::clear_pb_vec_int() {
  pb_vec_int_.Clear();
}
 ::google::protobuf::int32 PbMsg::pb_vec_int(int index) const {
  // @@protoc_insertion_point(field_get:examples.PbMsg.pb_vec_int)
  return pb_vec_int_.Get(index);
}
 void PbMsg::set_pb_vec_int(int index, ::google::protobuf::int32 value) {
  pb_vec_int_.Set(index, value);
  // @@protoc_insertion_point(field_set:examples.PbMsg.pb_vec_int)
}
 void PbMsg::add_pb_vec_int(::google::protobuf::int32 value) {
  pb_vec_int_.Add(value);
  // @@protoc_insertion_point(field_add:examples.PbMsg.pb_vec_int)
}
 const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
PbMsg::pb_vec_int() const {
  // @@protoc_insertion_point(field_list:examples.PbMsg.pb_vec_int)
  return pb_vec_int_;
}
 ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
PbMsg::mutable_pb_vec_int() {
  // @@protoc_insertion_point(field_mutable_list:examples.PbMsg.pb_vec_int)
  return &pb_vec_int_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace examples

// @@protoc_insertion_point(global_scope)
